export const GET_CANCEL_ORDER_REQUEST="GET_CANCEL_ORDER_REQUEST";
export const GET_CANCEL_ORDER_SUCCESS="GET_CANCEL_ORDER_SUCCESS";
export const GET_CANCEL_ORDER_FAILURE="GET_CANCEL_ORDER_FAILURE";

export const GET_COUNTRY_NAME_REQUEST="GET_COUNTRY_NAME_REQUEST";
export const GET_COUNTRY_NAME_SUCCESS="GET_COUNTRY_NAME_SUCCESS";
export const GET_COUNTRY_NAME_FAILURE="GET_COUNTRY_NAME_FAILURE";


export const ADD_DELIVERY_INFO_REQUEST="ADD_DELIVERY_INFO_REQUEST";
export const ADD_DELIVERY_INFO_SUCCESS="ADD_DELIVERY_INFO_SUCCESS";
export const ADD_DELIVERY_INFO_FAILURE="ADD_DELIVERY_INFO_FAILURE";

export const TRACK_ORDER_STATUS_REQUEST="TRACK_ORDER_STATUS_REQUEST";
export const TRACK_ORDER_STATUS_SUCCESS="TRACK_ORDER_STATUS_SUCCESS";
export const TRACK_ORDER_STATUS_FAILURE="TRACK_ORDER_STATUS_FAILURE";

export const GET_ORDER_STATUS_REQUEST="GET_ORDER_STATUS_REQUEST";
export const GET_ORDER_STATUS_SUCCESS="GET_ORDER_STATUS_SUCCESS";
export const GET_ORDER_STATUS_FAILURE="GET_ORDER_STATUS_FAILURE";

export const GET_CUSTOMER_LIST_REQUEST = "GET_CUSTOMER_LIST_REQUEST";
export const GET_CUSTOMER_LIST_SUCCESS = "GET_CUSTOMER_LIST_SUCCESS";
export const GET_CUSTOMER_LIST_FAILURE = "GET_CUSTOMER_LIST_FAILURE";

export const INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_REQUSET =
  "INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_REQUSET";
export const INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_SUCCESS =
  "INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_SUCCESS";
export const INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_FAILURE =
  "INPUT_CUSTOMER_PRODUCT_SEARCH_DATA_FAILURE";


  export const LINK_PRODUCT_INFO_REQUEST =
  "LINK_PRODUCT_INFO_REQUEST";
export const LINK_PRODUCT_INFO_SUCCESS =
  "LINK_PRODUCT_INFO_SUCCESS";
export const LINK_PRODUCT_INFO_FAILURE =
  "LINK_PRODUCT_INFO_FAILURE";

export const ADD_PLACE_ORDER_REQUEST="ADD_PLACE_ORDER_REQUEST";
export const ADD_PLACE_ORDER_SUCCESS="ADD_PLACE_ORDER_SUCCESS";
export const ADD_PLACE_ORDER_FAILURE="ADD_PLACE_ORDER_FAILURE";

export const GET_CART_ITEMS_REQUEST="GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS="GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAILURE="GET_CART_ITEMS_FAILURE";

export const GET_SHOP_IMAGE_REQUEST = "GET_SHOP_IMAGE_REQUEST";
export const GET_SHOP_IMAGE_SUCCESS = "GET_SHOP_IMAGE_SUCCESS";
export const GET_SHOP_IMAGE_FAILURE = "GET_SHOP_IMAGE_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST="GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS="GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE="GET_PRODUCT_BY_ID_FAILURE";

export const GET_CATEGORIES_REQUEST="GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE="GET_CATEGORIES_FAILURE";

export const ADD_CONTACT_DETAILS_REQUEST = "ADD_CONTACT_DETAILS_REQUEST";
export const ADD_CONTACT_DETAILS_SUCCESS = "ADD_CONTACT_DETAILS_SUCCESS";
export const ADD_CONTACT_DETAILS_FAILURE = "ADD_CONTACT_DETAILS_FAILURE";

export const GET_SOURCE_REQUEST = "GET_SOURCE_REQUEST";
export const GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS";
export const GET_SOURCE_FAILURE = "GET_SOURCE_FAILURE";

export const SET_CLEARBIT_DATA = "SET_CLEARBIT_DATA";

export const HANDLE_STRIPE_MODAL = 'HANDLE_STRIPE_MODAL';

export const GET_PAYMENT_ID_REQUEST = "GET_PAYMENT_ID_REQUEST";
export const GET_PAYMENT_ID_SUCCESS = "GET_PAYMENT_ID_SUCCESS";
export const GET_PAYMENT_ID_FAILURE= "GET_PAYMENT_ID_FAILURE";

export const GET_PRODUCT_BY_CATEGORY_ID_REQUEST="GET_PRODUCT_BY_CATEGORY_ID_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_ID_SUCCESS="GET_PRODUCT_BY_CATEGORY_ID_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_ID_FAILURE="GET_PRODUCT_BY_CATEGORY_ID_FAILURE";

export const GET_SUPPLIES_LIST_C_REQUEST = "GET_SUPPLIES_LIST_C_REQUEST";
export const GET_SUPPLIES_LIST_C_SUCCESS = "GET_SUPPLIES_LIST_C_SUCCESS";
export const GET_SUPPLIES_LIST_C_FAILURE = "GET_SUPPLIES_LIST_C_FAILURE";

export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_REQUEST="GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_REQUEST";
export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_SUCCESS="GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_SUCCESS";
export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_FAILURE="GET_ALL_INVENTORY_SUPPLIER_ITEMS_C_FAILURE";

export const GET_ALL_SUPPLIER_ITEMS_C_REQUEST="GET_ALL_SUPPLIER_ITEMS_C_REQUEST";
export const GET_ALL_SUPPLIER_ITEMS_C_SUCCESS="GET_ALL_SUPPLIER_ITEMS_C_SUCCESS";
export const GET_ALL_SUPPLIER_ITEMS_C_FAILURE="GET_ALL_SUPPLIER_ITEMS_C_FAILURE";