export const GET_TASK_BY_CANDIDATE_ID_REQUEST = "GET_TASK_BY_CANDIDATE_ID_REQUEST";
export const GET_TASK_BY_CANDIDATE_ID_SUCCESS = "GET_TASK_BY_CANDIDATE_ID_SUCCESS";
export const GET_TASK_BY_CANDIDATE_ID_FAILURE = "GET_TASK_BY_CANDIDATE_ID_FAILURE";

export const HANDLE_TASK_DRAWER_MODAL="HANDLE_TASK_DRAWER_MODAL";

export const HANDLE_NOTE_DRAWER_MODAL="HANDLE_NOTE_DRAWER_MODAL";

export const HANDLE_TASKNAME_DRAWER_MODAL="HANDLE_TASKNAME_DRAWER_MODAL";

export const UPDATE_TASK_STATUS_REQUEST = "UPDATE_TASK_STATUS_REQUEST";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_FAILURE = "UPDATE_TASK_STATUS_FAILURE";

export const ADD_TASK_HOUR_REQUEST = "ADD_TASK_HOUR_REQUEST";
export const ADD_TASK_HOUR_SUCCESS = "ADD_TASK_HOUR_SUCCESS";
export const ADD_TASK_HOUR_FAILURE = "ADD_TASK_HOUR_FAILURE";

export const ADD_OPPORTUNITY_NOTES_REQUEST = "ADD_OPPORTUNITY_NOTES_REQUEST";
export const ADD_OPPORTUNITY_NOTES_SUCCESS = "ADD_OPPORTUNITY_NOTES_SUCCESS";
export const ADD_OPPORTUNITY_NOTES_FAILURE = "ADD_OPPORTUNITY_NOTES_FAILURE";

export const GET_NOTES_LIST_BY_OPPORTUNITY_ID_REQUEST =
  "GET_NOTES_LIST_BY_OPPORTUNITY_ID_REQUEST";
export const GET_NOTES_LIST_BY_OPPORTUNITY_ID_SUCCESS =
  "GET_NOTES_LIST_BY_OPPORTUNITY_ID_SUCCESS";
export const GET_NOTES_LIST_BY_OPPORTUNITY_ID_FAILURE =
  "GET_NOTES_LIST_BY_OPPORTUNITY_ID_FAILURE";

  export const GET_TASK_NAME_REQUEST =
  "GET_TASK_NAME_REQUEST";
export const GET_TASK_NAME_SUCCESS =
  "GET_TASK_NAME_SUCCESS";
export const GET_TASK_NAME_FAILURE =
  "GET_TASK_NAME_FAILURE";