export const SET_ACHIEVEMENT_VIEW_TYPE = "SET_ACHIEVEMENT_VIEW_TYPE";

export const SET_TIME_INTERVAL_REPORT = "SET_TIME_INTERVAL_REPORT";

export const CHANGE_SELECTED_TIME_INTERVAL_REPORT =
  "CHANGE_SELECTED_TIME_INTERVAL_REPORT";

  
export const GET_DATE_WISE_ACHIEVEMENT_REQUEST = "GET_DATE_WISE_ACHIEVEMENT_REQUEST";
export const GET_DATE_WISE_ACHIEVEMENT_SUCCESS = "GET_DATE_WISE_ACHIEVEMENT_SUCCESS";
export const GET_DATE_WISE_ACHIEVEMENT_FAILURE = "GET_DATE_WISE_ACHIEVEMENT_FAILURE";