
export const GET_PROFESSIONALDUCTS_REQUEST = "GET_PROFESSIONALDUCTS_REQUEST";
export const GET_PROFESSIONALDUCTS_SUCCESS = "GET_PROFESSIONALDUCTS_SUCCESS";
export const GET_PROFESSIONALDUCTS_FAILURE = "GET_PROFESSIONALDUCTS_FAILURE";

export const GET_ALL_PRODUCT_CATEGORY_REQUEST = "GET_ALL_PRODUCT_CATEGORY_REQUEST";
export const GET_ALL_PRODUCT_CATEGORY_SUCCESS = "GET_ALL_PRODUCT_CATEGORY_SUCCESS";
export const GET_ALL_PRODUCT_CATEGORY_FAILURE = "GET_ALL_PRODUCT_CATEGORY_FAILURE";

export const GET_ALL_SUPPLIES_CATEGORY_REQUEST = "GET_ALL_SUPPLIES_CATEGORY_REQUEST";
export const GET_ALL_SUPPLIES_CATEGORY_SUCCESS = "GET_ALL_SUPPLIES_CATEGORY_SUCCESS";
export const GET_ALL_SUPPLIES_CATEGORY_FAILURE = "GET_ALL_SUPPLIES_CATEGORY_FAILURE";

export const HANDLE_UPLOAD_INVENTORY_DRAWER="HANDLE_UPLOAD_INVENTORY_DRAWER";

export const UPLOAD_UPLOAD_INVENTORY_REQUEST = "UPLOAD_UPLOAD_INVENTORY_REQUEST";
export const UPLOAD_UPLOAD_INVENTORY_SUCCESS = "UPLOAD_UPLOAD_INVENTORY_SUCCESS";
export const UPLOAD_UPLOAD_INVENTORY_FAILURE = "UPLOAD_UPLOAD_INVENTORY_FAILURE";

export const LINK_INVENTORY_ITEM_REQUEST = "LINK_INVENTORY_ITEM_REQUEST";
export const LINK_INVENTORY_ITEM_SUCCESS = "LINK_INVENTORY_ITEM_SUCCESS";
export const LINK_INVENTORY_ITEM_FAILURE = "LINK_INVENTORY_ITEM_FAILURE";
export const GET_INVENTORY_CART_ITEMS_REQUEST = "GET_INVENTORY_CART_ITEMS_REQUEST";
export const GET_INVENTORY_CART_ITEMS_SUCCESS = "GET_INVENTORY_CART_ITEMS_SUCCESS";
export const GET_INVENTORY_CART_ITEMS_FAILURE = "GET_INVENTORY_CART_ITEMS_FAILURE";

export const ADD_INVENTORY_DELIVERY_INFO_REQUEST="ADD_INVENTORY_DELIVERY_INFO_REQUEST";
export const ADD_INVENTORY_DELIVERY_INFO_SUCCESS="ADD_INVENTORY_DELIVERY_INFO_SUCCESS";
export const ADD_INVENTORY_DELIVERY_INFO_FAILURE="ADD_INVENTORY_DELIVERY_INFO_FAILURE";

export const HANDLE_INVENTORY_STRIPE_MODAL="HANDLE_INVENTORY_STRIPE_MODAL";

export const ADD_INVENTORY_PAYMENT_ID_REQUEST="ADD_INVENTORY_PAYMENT_ID_REQUEST";
export const ADD_INVENTORY_PAYMENT_ID_SUCCESS="ADD_INVENTORY_PAYMENT_ID_SUCCESS";
export const ADD_INVENTORY_PAYMENT_ID_FAILURE="ADD_INVENTORY_PAYMENT_ID_FAILURE";

export const MAKE_INVENTORY_PAYMENT_REQUEST="MAKE_INVENTORY_PAYMENT_REQUEST";
export const MAKE_INVENTORY_PAYMENT_SUCCESS="MAKE_INVENTORY_PAYMENT_SUCCESS";
export const MAKE_INVENTORY_PAYMENT_FAILURE="MAKE_INVENTORY_PAYMENT_FAILURE";

export const GET_INVENTORY_CART_ITEMS_COUNT_REQUEST = "GET_INVENTORY_CART_ITEMS_COUNT_REQUEST";
export const GET_INVENTORY_CART_ITEMS_COUNT_SUCCESS = "GET_INVENTORY_CART_ITEMS_COUNT_SUCCESS";
export const GET_INVENTORY_CART_ITEMS_COUNT_FAILURE = "GET_INVENTORY_CART_ITEMS_COUNT_FAILURE";

export const UPDATE_CART_PLUS_REQUEST="UPDATE_CART_PLUS_REQUEST";
export const UPDATE_CART_PLUS_SUCCESS="UPDATE_CART_PLUS_SUCCESS";
export const UPDATE_CART_PLUS_FAILURE="UPDATE_CART_PLUS_FAILURE";

export const DELETE_CART_ITEM_REQUEST="DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS="DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILURE="DELETE_CART_ITEM_FAILURE";

export const ADD_COD_INVENTORY_REQUEST="ADD_COD_INVENTORY_REQUEST";
export const ADD_COD_INVENTORY_SUCCESS="ADD_COD_INVENTORY_SUCCESS";
export const ADD_COD_INVENTORY_FAILURE="ADD_COD_INVENTORY_FAILURE";

export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_REQUEST="GET_ALL_INVENTORY_SUPPLIER_ITEMS_REQUEST";
export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_SUCCESS="GET_ALL_INVENTORY_SUPPLIER_ITEMS_SUCCESS";
export const GET_ALL_INVENTORY_SUPPLIER_ITEMS_FAILURE="GET_ALL_INVENTORY_SUPPLIER_ITEMS_FAILURE";

export const GET_ALL_SUPPLIER_ITEMS_REQUEST="GET_ALL_SUPPLIER_ITEMS_REQUEST";
export const GET_ALL_SUPPLIER_ITEMS_SUCCESS="GET_ALL_SUPPLIER_ITEMS_SUCCESS";
export const GET_ALL_SUPPLIER_ITEMS_FAILURE="GET_ALL_SUPPLIER_ITEMS_FAILURE";

export const GET_SUPPLIES_LIST_REQUEST = "GET_SUPPLIES_LIST_REQUEST";
export const GET_SUPPLIES_LIST_SUCCESS = "GET_SUPPLIES_LIST_SUCCESS";
export const GET_SUPPLIES_LIST_FAILURE = "GET_SUPPLIES_LIST_FAILURE";

export const GET_SUPLR_INVENTORY_LIST_REQUEST = "GET_SUPLR_INVENTORY_LIST_REQUEST";
export const GET_SUPLR_INVENTORY_LIST_SUCCESS = "GET_SUPLR_INVENTORY_LIST_SUCCESS";
export const GET_SUPLR_INVENTORY_LIST_FAILURE = "GET_SUPLR_INVENTORY_LIST_FAILURE";

export const UPDATE_CART_ITEM_DATE_REQUEST = "UPDATE_CART_ITEM_DATE_REQUEST";
export const UPDATE_CART_ITEM_DATE_SUCCESS = "UPDATE_CART_ITEM_DATE_SUCCESS";
export const UPDATE_CART_ITEM_DATE_FAILURE = "UPDATE_CART_ITEM_DATE_FAILURE";

export const HANDLE_ADD_SUPLR_INVENTORY_DRAWER="HANDLE_ADD_SUPLR_INVENTORY_DRAWER";

export const ADD_SUPLR_INVENTORY_REQUEST = "ADD_SUPLR_INVENTORY_REQUEST";
export const ADD_SUPLR_INVENTORY_SUCCESS = "UPDATE_CART_ITEM_DATE_SUCCESS";
export const ADD_SUPLR_INVENTORY_FAILURE = "ADD_SUPLR_INVENTORY_FAILURE";

export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE = "GET_BRAND_FAILURE";

export const GET_MODEL_REQUEST = "GET_MODEL_REQUEST";
export const GET_MODEL_SUCCESS = "GET_MODEL_SUCCESS";
export const GET_MODEL_FAILURE = "GET_MODEL_FAILURE";

export const GET_ALL_PRODUCT_LIST_REQUEST = "GET_ALL_PRODUCT_LIST_REQUEST";
export const GET_ALL_PRODUCT_LIST_SUCCESS = "GET_ALL_PRODUCT_LIST_SUCCESS";
export const GET_ALL_PRODUCT_LIST_FAILURE = "GET_ALL_PRODUCT_LIST_FAILURE";

export const GET_LOCATION_LIST_REQUEST =
  "GET_LOCATION_LIST_REQUEST";
export const GET_LOCATION_LIST_SUCCESS =
  "GET_LOCATION_LIST_SUCCESS";
export const GET_LOCATION_LIST_FAILURE =
  "GET_LOCATION_LIST_FAILURE";

export const GET_SALE_CURRENCY_REQUEST = "GET_SALE_CURRENCY_REQUEST";
export const GET_SALE_CURRENCY_SUCCESS = "GET_SALE_CURRENCY_SUCCESS";
export const GET_SALE_CURRENCY_FAILURE = "GET_SALE_CURRENCY_FAILURE";

export const HANDLE_PRODUCTS_DETAILS_DRAWER = "HANDLE_PRODUCTS_DETAILS_DRAWER";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const GET_FEATURED_MATERIALS_REQUEST = "GET_FEATURED_MATERIALS_REQUEST";
export const GET_FEATURED_MATERIALS_SUCCESS = "GET_FEATURED_MATERIALS_SUCCESS";
export const GET_FEATURED_MATERIALS_FAILURE = "GET_FEATURED_MATERIALS_FAILURE";