export const HANDLE_REVIEW_OFFER_MODAL = "HANDLE_REVIEW_OFFER_MODAL"

export const HANDLE_ADD_ORDER_MODAL = "HANDLE_ADD_ORDER_MODAL"

export const HANDLE_ORDERED_PHONE_MODAL = "HANDLE_ORDERED_PHONE_MODAL"

export const HANDLE_SEE_DETAILS_MODAL = "HANDLE_SEE_DETAILS_MODAL"

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";


export const ADD_PHONE_REQUEST = "ADD_PHONE_REQUEST";
export const ADD_PHONE_SUCCESS = "ADD_PHONE_SUCCESS";
export const ADD_PHONE_FAILURE = "ADD_PHONE_FAILURE";

export const CONFIRM_BUTTON_CLICK_REQUEST = "CONFIRM_BUTTON_CLICK_REQUEST";
export const CONFIRM_BUTTON_CLICK_SUCCESS = "CONFIRM_BUTTON_CLICK_SUCCESS";
export const CONFIRM_BUTTON_CLICK_FAILURE = "CONFIRM_BUTTON_CLICK_FAILURE";

export const GET_PHONE_DETAILS_REQUEST = "GET_PHONE_DETAILS_REQUEST";
export const GET_PHONE_DETAILS_SUCCESS = "GET_PHONE_DETAILS_SUCCESS";
export const GET_PHONE_DETAILS_FAILURE = "GET_PHONE_DETAILS_FAILURE"

export const GET_ORDER_DATA_REQUEST = "GET_ORDER_DATA_REQUEST";
export const GET_ORDER_DATA_SUCCESS = "GET_ORDER_DATA_SUCCESS";
export const GET_ORDER_DATA_FAILURE = "GET_ORDER_DATA_FAILURE";

export const HANDLE_PHONE_LIST_ORDER_NOTE_MODAL = "HANDLE_PHONE_LIST_ORDER_NOTE_MODAL";
// export const HANDLE_PHONE_LIST_ORDER_TASK_MODAL="HANDLE_PHONE_LIST_ORDER_TASK_MODAL";

export const HANDLE_PICK_UP_MODAL = "HANDLE_PICK_UP_MODAL";

export const ADD_PICKUP_ADDRESS_REQUEST = "ADD_PICKUP_ADDRESS_REQUEST";
export const ADD_PICKUP_ADDRESS_SUCCESS = "ADD_PICKUP_ADDRESS_SUCCESS";
export const ADD_PICKUP_ADDRESS_FAILURE = "ADD_PICKUP_ADDRESS_FAILURE";

export const HANDLE_STATUS_OF_ORDER_MODAL = "HANDLE_STATUS_OF_ORDER_MODAL";

export const GET_STATUS_OF_ORDER_REQUEST = "GET_STATUS_OF_ORDER_REQUEST";
export const GET_STATUS_OF_ORDER_SUCCESS = "GET_STATUS_OF_ORDER_SUCCESS";
export const GET_STATUS_OF_ORDER_FAILURE = "GET_STATUS_OF_ORDER_FAILURE";

export const HANDLE_FEEDBACK_ORDER_DRAWER="HANDLE_FEEDBACK_ORDER_DRAWER";

export const POST_FEEDBACK_REQUEST = "POST_FEEDBACK_REQUEST";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_FAILURE = "POST_FEEDBACK_FAILURE";

export const GET_FEEDBACK_REQUEST = "GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAILURE = "GET_FEEDBACK_FAILURE";

export const HANDLE_FEEDBACK_PHONE_ORDER_DRAWER="HANDLE_FEEDBACK_PHONE_ORDER_DRAWER";

export const GET_NOTES_LIST_IN_ORDER_REQUEST = "GET_NOTES_LIST_IN_ORDER_REQUEST";
export const GET_NOTES_LIST_IN_ORDER_SUCCESS = "GET_NOTES_LIST_IN_ORDER_SUCCESS";
export const GET_NOTES_LIST_IN_ORDER_FAILURE = "GET_NOTES_LIST_IN_ORDER_FAILURE";

export const GET_ORDER_COUNT_REQUEST = "GET_ORDER_COUNT_REQUEST";
export const GET_ORDER_COUNT_SUCCESS = "GET_ORDER_COUNT_SUCCESS";
export const GET_ORDER_COUNT_FAILURE = "GET_ORDER_COUNT_FAILURE";

export const GET_COMPLETED_ORDER_REQUEST = "GET_COMPLETED_ORDER_REQUEST";
export const GET_COMPLETED_ORDER_SUCCESS = "GET_COMPLETED_ORDER_SUCCESS";
export const GET_COMPLETED_ORDER_FAILURE = "GET_COMPLETED_ORDER_FAILURE";

export const GET_INCOMPLETED_ORDER_REQUEST = "GET_INCOMPLETED_ORDER_REQUEST";
export const GET_INCOMPLETED_ORDER_SUCCESS = "GET_INCOMPLETED_ORDER_SUCCESS";
export const GET_INCOMPLETED_ORDER_FAILURE = "GET_INCOMPLETED_ORDER_FAILURE";

export const GET_CANCEL_ORDER_REQUEST = "GET_CANCEL_ORDER_REQUEST";
export const GET_CANCEL_ORDER_SUCCESS = "GET_CANCEL_ORDER_SUCCESS";
export const GET_CANCEL_ORDER_FAILURE = "GET_CANCEL_ORDER_FAILURE";

export const GET_TOTAL_ORDER_REQUEST = "GET_TOTAL_ORDER_REQUEST";
export const GET_TOTAL_ORDER_SUCCESS = "GET_TOTAL_ORDER_SUCCESS";
export const GET_TOTAL_ORDER_FAILURE = "GET_TOTAL_ORDER_FAILURE";

export const HANDLE_ORDER_OPEN_MODAL = "HANDLE_ORDER_OPEN_MODAL";

export const GET_TASK_LIST_BY_PHONE_REQUEST = "GET_TASK_LIST_BY_PHONE_REQUEST";
export const GET_TASK_LIST_BY_PHONE_SUCCESS = "GET_TASK_LIST_BY_PHONE_SUCCESS";
export const GET_TASK_LIST_BY_PHONE_FAILURE = "GET_TASK_LIST_BY_PHONE_FAILURE";

export const GET_TASK_BY_PHONEID_REQUEST = "GET_TASK_BY_PHONEID_REQUEST";
export const GET_TASK_BY_PHONEID_SUCCESS = "GET_TASK_BY_PHONEID_SUCCESS";
export const GET_TASK_BY_PHONEID_FAILURE = "GET_TASK_BY_PHONEID_FAILURE";

export const HANDLE_STAR_ORDER_DRAWER = "HANDLE_STAR_ORDER_DRAWER";

export const GET_PROCURE_ORDER_DATA_REQUEST = "GET_PROCURE_ORDER_DATA_REQUEST";
export const GET_PROCURE_ORDER_DATA_SUCCESS = "GET_PROCURE_ORDER_DATA_SUCCESS";
export const GET_PROCURE_ORDER_DATA_FAILURE = "GET_PROCURE_ORDER_DATA_FAILURE";

export const HANDLE_ITEM_VIEW_DRAWER = "HANDLE_ITEM_VIEW_DRAWER";
export const HANDLE_STATUS_SHOW_DRAWER = "HANDLE_STATUS_SHOW_DRAWER";

export const GET_PROCURE_QUOTATION_REQUEST = "GET_PROCURE_QUOTATION_REQUEST";
export const GET_PROCURE_QUOTATION_SUCCESS = "GET_PROCURE_QUOTATION_SUCCESS";
export const GET_PROCURE_QUOTATION_FAILURE = "GET_PROCURE_QUOTATION_FAILURE";

export const GET_PROCURE_ORDER_DETAILS_REQUEST = "GET_PROCURE_ORDER_DETAILS_REQUEST";
export const GET_PROCURE_ORDER_DETAILS_SUCCESS = "GET_PROCURE_ORDER_DETAILS_SUCCESS";
export const GET_PROCURE_ORDER_DETAILS_FAILURE = "GET_PROCURE_ORDER_DETAILS_FAILURE";

export const GET_PROCURE_STATUS_ITEM_REQUEST = "GET_PROCURE_STATUS_ITEM_REQUEST";
export const GET_PROCURE_STATUS_ITEM_SUCCESS = "GET_PROCURE_STATUS_ITEM_SUCCESS";
export const GET_PROCURE_STATUS_ITEM_FAILURE = "GET_PROCURE_STATUS_ITEM_FAILURE";

export const GET_ORDER_SUPPLIER_LIST_REQUEST = "GET_ORDER_SUPPLIER_LIST_REQUEST";
export const GET_ORDER_SUPPLIER_LIST_SUCCESS = "GET_ORDER_SUPPLIER_LIST_SUCCESS";
export const GET_ORDER_SUPPLIER_LIST_FAILURE = "GET_ORDER_SUPPLIER_LIST_FAILURE";

export const GET_ODR_SUPPLIER_ITEMS_REQUEST = "GET_ODR_SUPPLIER_ITEMS_REQUEST";
export const GET_ODR_SUPPLIER_ITEMS_SUCCESS = "GET_ODR_SUPPLIER_ITEMS_SUCCESS";
export const GET_ODR_SUPPLIER_ITEMS_FAILURE = "GET_ODR_SUPPLIER_ITEMS_FAILURE";

export const GET_ODR_SUPPLIER_REQUEST = "GET_ODR_SUPPLIER_REQUEST";
export const GET_ODR_SUPPLIER_SUCCESS = "GET_ODR_SUPPLIER_SUCCESS";
export const GET_ODR_SUPPLIER_FAILURE = "GET_ODR_SUPPLIER_FAILURE";

export const GET_TOP_SELL_REQUEST = "GET_TOP_SELL_REQUEST";
export const GET_TOP_SELL_SUCCESS = "GET_TOP_SELL_SUCCESS";
export const GET_TOP_SELL_FAILURE = "GET_TOP_SELL_FAILURE";

export const GET_LEAST_SELL_REQUEST = "GET_LEAST_SELL_REQUEST";
export const GET_LEAST_SELL_SUCCESS = "GET_LEAST_SELL_SUCCESS";
export const GET_LEAST_SELL_FAILURE = "GET_LEAST_SELL_FAILURE";

export const REPEAT_ORDER_REQUEST = "REPEAT_ORDER_REQUEST";
export const REPEAT_ORDER_SUCCESS = "REPEAT_ORDER_SUCCESS";
export const REPEAT_ORDER_FAILURE = "REPEAT_ORDER_FAILURE";

export const UPDATE_ORDR_SUPLR_ITEMS_REQUEST = "UPDATE_ORDR_SUPLR_ITEMS_REQUEST";
export const UPDATE_ORDR_SUPLR_ITEMS_SUCCESS = "UPDATE_ORDR_SUPLR_ITEMS_SUCCESS";
export const UPDATE_ORDR_SUPLR_ITEMS_FAILURE = "UPDATE_ORDR_SUPLR_ITEMS_FAILURE";

export const GET_ORDR_SUPLR_DETAILS_REQUEST = "GET_ORDR_SUPLR_DETAILS_REQUEST";
export const GET_ORDR_SUPLR_DETAILS_SUCCESS = "GET_ORDR_SUPLR_DETAILS_SUCCESS";
export const GET_ORDR_SUPLR_DETAILS_FAILURE = "GET_ORDR_SUPLR_DETAILS_FAILURE";

export const GET_SUPPLIER_ORDR_ITEM_LIST_REQUEST = "GET_SUPPLIER_ORDR_ITEM_LIST_REQUEST";
export const GET_SUPPLIER_ORDR_ITEM_LIST_SUCCESS = "GET_SUPPLIER_ORDR_ITEM_LIST_SUCCESS";
export const GET_SUPPLIER_ORDR_ITEM_LIST_FAILURE = "GET_SUPPLIER_ORDR_ITEM_LIST_FAILURE";