export const GET_ALL_PURCHASE_ORDER_REQUEST = "GET_ALL_PURCHASE_ORDER_REQUEST";
export const GET_ALL_PURCHASE_ORDER_SUCCESS = "GET_ALL_PURCHASE_ORDER_SUCCESS";
export const GET_ALL_PURCHASE_ORDER_FAILURE = "GET_ALL_PURCHASE_ORDER_FAILURE";

export const HNADLE_PO_TRACK_MODAL = "HNADLE_PO_TRACK_MODAL"

export const HNADLE_PO_SUMMARY_MODAL = "HNADLE_PO_SUMMARY_MODAL"

export const GET_PO_LIST_REQUEST = "GET_PO_LIST_REQUEST";
export const GET_PO_LIST_SUCCESS = "GET_PO_LIST_SUCCESS";
export const GET_PO_LIST_FAILURE = "GET_PO_LIST_FAILURE";


export const GET_PO_STAGE_REQUEST = "GET_PO_STAGE_REQUEST";
export const GET_PO_STAGE_SUCCESS = "GET_PO_STAGE_SUCCESS";
export const GET_PO_STAGE_FAILURE = "GET_PO_STAGE_FAILURE";

export const HNADLE_ITEM_TRACK_MODAL = "HNADLE_ITEM_TRACK_MODAL"

export const GET_LOCATION_DETAILS_FOR_PO_UPDATE_REQUEST = "GET_LOCATION_DETAILS_FOR_PO_UPDATE_REQUEST";
export const GET_LOCATION_DETAILS_FOR_PO_UPDATE_SUCCESS = "GET_LOCATION_DETAILS_FOR_PO_UPDATE_SUCCESS";
export const GET_LOCATION_DETAILS_FOR_PO_UPDATE_FAILURE = "GET_LOCATION_DETAILS_FOR_PO_UPDATE_FAILURE";

export const GET_PO_DETAILS_LIST_REQUEST = "GET_PO_DETAILS_LIST_REQUEST";
export const GET_PO_DETAILS_LIST_SUCCESS = "GET_PO_DETAILS_LIST_SUCCESS";
export const GET_PO_DETAILS_LIST_FAILURE = "GET_PO_DETAILS_LIST_FAILURE";