
export const VALIDATE_OTP_BY_EMAIL_REQUEST = "VALIDATE_OTP_BY_EMAIL_REQUEST";
export const VALIDATE_OTP_BY_EMAIL_SUCCESS = "VALIDATE_OTP_BY_EMAIL_SUCCESS";
export const VALIDATE_OTP_BY_EMAIL_FAILURE = "VALIDATE_OTP_BY_EMAIL_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GENERATE_OTP_BY_EMAIL_REQUEST = "GENERATE_OTP_BY_EMAIL_REQUEST";
export const GENERATE_OTP_BY_EMAIL_SUCCESS = "GENERATE_OTP_BY_EMAIL_SUCCESS";
export const GENERATE_OTP_BY_EMAIL_FAILURE = "GENERATE_OTP_BY_EMAIL_FAILURE";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const GET_ACHIVEMENT_REQUEST =
  "GET_ACHIVEMENT_REQUEST";
export const GET_ACHIVEMENT_SUCCESS =
  "GET_ACHIVEMENT_SUCCESS";
export const GET_ACHIVEMENT_FAILURE =
  "GET_ACHIVEMENT_FAILURE";

  export const HANDLE_ACHIEVEMENT_DRAWER_MODAL="HANDLE_ACHIEVEMENT_DRAWER_MODAL";

  export const SET_CLEARBIT_DATA = "SET_CLEARBIT_DATA";

export const ADD_CONTACT_DETAILS_REQUEST = "ADD_CONTACT_DETAILS_REQUEST";
export const ADD_CONTACT_DETAILS_SUCCESS = "ADD_CONTACT_DETAILS_SUCCESS";
export const ADD_CONTACT_DETAILS_FAILURE = "ADD_CONTACT_DETAILS_FAILURE";
