export const GET_PAST_NOTIFICATIONS_REQUEST = "GET_PAST_NOTIFICATIONS_REQUEST";
export const GET_PAST_NOTIFICATIONS_SUCCESS = "GET_PAST_NOTIFICATIONS_SUCCESS";
export const GET_PAST_NOTIFICATIONS_FAILURE = "GET_PAST_NOTIFICATIONS_FAILURE";

export const GET_PRESENT_NOTIFICATIONS_REQUEST =
  "GET_PRESENT_NOTIFICATIONS_REQUEST";
export const GET_PRESENT_NOTIFICATIONS_SUCCESS =
  "GET_PRESENT_NOTIFICATIONS_SUCCESS";
export const GET_PRESENT_NOTIFICATIONS_FAILURE =
  "GET_PRESENT_NOTIFICATIONS_FAILURE";


export const FETCHING_NOTIFICATIONS = "FETCHING_NOTIFICATIONS";
